### ISSUE TITLE
[前] 全站搜尋hover Pen後遮到藍色線

### ISSUE THREAD

**Issue by VincentYuuu** [6yCRYSTAL/codepain#396]
![image](https://user-images.githubusercontent.com/62990820/121981662-ae807080-cdc0-11eb-9a3e-bef544d719ec.png)
![image](https://user-images.githubusercontent.com/62990820/121981736-c9eb7b80-cdc0-11eb-880e-aca06fc25a6b.png)

**Comment by cyhsujohn** [comment]
那個其實是故意的效果，可能需要把search 那條藍線下面的空間撐開一點，就不會像是寫錯

**Comment by VincentYuuu** [comment]
這邊指的是hover後Pen的after背景撐到藍色的線了，可在藍色線上加個margin-bottom把下方的Pen撐開就可以
